Repository s1seven/schema-tools, pull requests merged in 2022-03, with the labels that each got.

#116 feat: add new CLI tools, make quantity and quantityUnit optional
  README.md
  fixtures/CoA/v0.1.1/certificate.ts
  fixtures/CoA/v0.1.1/template_hbs.html
  fixtures/CoA/v0.1.1/translations.json
  fixtures/CoA/v0.1.1/valid_cert.json
  fixtures/CoA/v0.1.1/valid_cert.pdf
  package-lock.json
  package.json
  packages/generate-coa-pdf-template/package.json
  packages/generate-coa-pdf-template/src/generateContent.ts
  packages/generate-coa-pdf-template/src/types/schemaTypes.ts
  packages/generate-html/README.md
  packages/generate-pdf/test/generate-pdf.spec.ts
  utils/create-html-certificate.js
  utils/create-pdf-certificate.js
  utils/create-schema-interfaces-interactive.js
  utils/create-schema-interfaces.js
Labels: bug, documentation, enhancement

#121 fix: cannot read properties of null
  .husky/commit-msg
  .husky/pre-commit
  README.md
  commitlint.config.js
  package-lock.json
  package.json
  packages/certificate-summary/src/index.ts
  packages/versioning/src/repository.ts
  packages/versioning/test/repository.spec.ts
Labels: bug, enhancement

#122 feat(versioning): allow passing `extraTranslations`
  packages/versioning/package.json
  packages/versioning/src/repository.ts
  packages/versioning/test/repository.spec.ts
Labels: enhancement

#130 chore: add official CoA v0.2.0 support
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  fixtures/CoA/v0.2.0/certificate.ts
  fixtures/CoA/v0.2.0/extra_translations.json
  fixtures/CoA/v0.2.0/template_hbs.html
  fixtures/CoA/v0.2.0/translations.json
  fixtures/CoA/v0.2.0/valid_cert.pdf
  fixtures/EN10168/v0.2.0/template_hbs.html
  fixtures/EN10168/v0.2.0/valid_cert.pdf
  packages/certificate-summary/test/certificate-summary.spec.ts
  packages/extract-emails/test/extract-emails.spec.ts
  packages/generate-coa-pdf-template/package.json
  packages/generate-coa-pdf-template/src/types/schemaTypes.ts
  packages/generate-html/example_campus.js
  packages/generate-html/test/generate-html.spec.ts
  packages/generate-interfaces/test/generate-interfaces.spec.ts
  packages/generate-pdf/example.js
  packages/generate-pdf/example_coa.js
  packages/generate-pdf/package.json
  packages/generate-pdf/test/generate-pdf.spec.ts
Labels: documentation, enhancement
