Repository s1seven/schema-tools, pull requests merged in 2024-03, with the labels that each got.

#252 chore: update deps and run nx migrate, improve release process
  README.md
  migrations.json
  nx.json
  package-lock.json
  package.json
  packages/versioning/package.json
Labels: documentation, dependencies

#254 fix: fix failing ci on nx release publish
  .github/workflows/node.yml
  README.md
  nx.json
  package-lock.json
Labels: bug, dependencies

#248 perf: monitor pdf generation performance
  .github/sync.yml
  .github/workflows/node.yml
  .vscode/launch.json
  README.md
  nx.json
  package-lock.json
  package.json
  packages/certificate-model/CHANGELOG.md
  packages/certificate-model/project.json
  packages/certificate-summary/CHANGELOG.md
  packages/certificate-summary/project.json
  packages/extract-emails/CHANGELOG.md
  packages/extract-emails/project.json
  packages/generate-coa-pdf-template/CHANGELOG.md
  packages/generate-coa-pdf-template/dist/generateContent.cjs
  packages/generate-coa-pdf-template/package.json
  packages/generate-coa-pdf-template/project.json
  packages/generate-coa-pdf-template/utils/create-example.ts
  packages/generate-coa-pdf-template/utils/styles.ts
  packages/generate-en10168-pdf-template/CHANGELOG.md
  packages/generate-en10168-pdf-template/dist/generateContent.cjs
  packages/generate-en10168-pdf-template/package.json
  packages/generate-en10168-pdf-template/project.json
  packages/generate-en10168-pdf-template/utils/create-example.ts
  packages/generate-html/CHANGELOG.md
  packages/generate-html/project.json
  packages/generate-interfaces/CHANGELOG.md
  packages/generate-interfaces/project.json
  packages/generate-pdf-template-helpers/CHANGELOG.md
  packages/generate-pdf-template-helpers/project.json
  packages/generate-pdf/CHANGELOG.md
  packages/generate-pdf/README.md
  packages/generate-pdf/example.ts
  packages/generate-pdf/example_coa.ts
  packages/generate-pdf/project.json
  packages/generate-pdf/test/generate-pdf.spec.ts
  packages/types/CHANGELOG.md
  packages/types/project.json
  packages/utils/project.json
  packages/validate/project.json
  packages/versioning/CHANGELOG.md
  packages/versioning/project.json
  utils/generate-fixtures-from-json.ts
Labels: dependencies, perf
